
import { useState, useEffect, useCallback } from 'react'; // Added useCallback

// Hoisted MOCK_TRANSLATIONS to be a constant outside the hook
const MOCK_TRANSLATIONS = {
    'en': {
        'common.error': 'Error',
        'common.featureComingSoonDetailed': 'Full {{featureName}} capabilities will be available soon.',
        'buttons.viewError': 'View Error',
        'buttons.enable': 'Enable',
        'buttons.disable': 'Disable',
        'buttons.configure': 'Configure',
        'buttons.learnMore': 'Learn More',
        'buttons.manage': 'Manage',
        'pageTitles.networkManagement': 'Network Management',
        'networkManagement.pageDescription': 'Manage providers, doctors, and their affiliations.',
        'pageTitles.providerDoctorLinkageShort': 'Linkage', // For shorter tab label
        'adminSettings.systemHealth.title': 'System Health Dashboard',
        'adminSettings.systemHealth.pageDescription': 'Overview of system component statuses and performance metrics.',
        'adminSettings.systemHealth.databaseService': 'Database Service',
        'adminSettings.systemHealth.apiGateway': 'API Gateway',
        'adminSettings.systemHealth.backgroundJobs': 'Background Job Processor',
        'adminSettings.systemHealth.securityServices': 'Security Services',
        'adminSettings.systemHealth.systemLoad': 'Overall System Load',
        'adminSettings.systemHealth.loadDescription': 'Current CPU and memory utilization.',
        'adminSettings.systemHealth.status.operational': 'Operational',
        'adminSettings.systemHealth.status.degraded_performance': 'Degraded Performance',
        'adminSettings.systemHealth.status.outage': 'Outage',
        'adminSettings.integrations.title': 'Manage Integrations',
        'adminSettings.integrations.pageDescription': 'Connect and configure third-party services and APIs.',
        'adminSettings.integrations.emailService.name': 'Transactional Email Service',
        'adminSettings.integrations.emailService.desc': 'For sending system notifications and alerts.',
        'adminSettings.integrations.paymentGateway.name': 'Payment Gateway',
        'adminSettings.integrations.paymentGateway.desc': 'To process payments for premium features.',
        'adminSettings.integrations.analytics.name': 'External Analytics Platform',
        'adminSettings.integrations.analytics.desc': 'Sync data with your preferred analytics tool.',
        'adminSettings.integrations.reportingApi.name': 'External Reporting API',
        'adminSettings.integrations.reportingApi.desc': 'Connect to external reporting systems.',
        'integrationStatus.active': 'Active',
        'integrationStatus.inactive': 'Inactive',
        'integrationStatus.pending_configuration': 'Pending Configuration',
        'integrationStatus.error': 'Error',
        'errors.rateLimitExceeded': 'Service is temporarily busy. Please try again in a few moments.',
        'errors.genericApiError': 'An error occurred. Please try again.',
        'errors.genericFetchError': 'Could not load data.',
        'common.success': 'Success',
        'common.warning': 'Warning',
        'errors.fetchDropdownError': 'Failed to load filter options.',
        'common.notSet': 'N/A',
        'common.invalidDate': 'Invalid Date',
        'common.confirmDelete': 'Are you sure you want to delete this item?',
        'common.deleteSuccess': 'Item deleted successfully.',
        'common.deleteError': 'Failed to delete item.',
        'common.updateSuccess': 'Item updated successfully.',
        'common.createSuccess': 'Item created successfully.',
        'common.saveError': 'Failed to save item.',
        'common.featureComingSoonTitle': 'Feature Coming Soon',
        'insurance.insuredPersons.dialogComingSoon': 'The dialog for adding/editing insured persons will be implemented soon.',
        'rfc.dialogComingSoon': 'The dialog for RFCs will be implemented soon.',
        'common.createdOn': 'Created',
        'fields.procedureDate': 'Procedure Date',
        'fields.insured': 'Insured',
        'fields.provider': 'Provider',
        'fields.doctor': 'Doctor',
        'fields.policyNumber': 'Policy #',
        'fields.procedures': 'Procedures',
        'fields.approvedAmount': 'Approved Amt',
        'buttons.viewDetails': 'View Details',
        'rfc.viewDetailsComingSoon': 'Viewing RFC details will be available soon.',
        'rfc.titleMultiple': 'Requests for Commitment',
        'buttons.addNewRFC': 'New RFC',
        'search.placeholderRFC': 'Search RFCs...',
        'filters.allStatuses': 'All Statuses',
        'status.draft': 'Draft',
        'status.submitted': 'Submitted',
        'status.inReview': 'In Review',
        'status.approved': 'Approved',
        'status.rejected': 'Rejected',
        'filters.selectStatus': 'Select Status',
        'filters.selectProvider': 'Select Provider',
        'filters.allProviders': 'All Providers',
        'buttons.resetFilters': 'Reset Filters',
        'buttons.refresh': 'Refresh',
        'buttons.retry': 'Retry',
        'messages.loadingData': 'Loading {{item}}...',
        'rfc.noRFCsMatchTitle': 'No RFCs Match Filters',
        'rfc.noRFCsMatchFilterDesc': 'Try adjusting filters or create a new RFC.',
        'rfc.noRFCsDesc': 'No RFCs found. Start by creating a new request for commitment.',
        'common.unknown': 'Unknown',
        'fields.created': 'Created',
        'fields.notes': 'Notes',
        'errors.partialLoadFailure': 'Some data could not be loaded. Functionality may be limited. Please refresh to try again.',
        'errors.fetchFailedSingular': 'Failed to load {{entity}}.',
        'insurance.insuredPersons.title': 'Insured Persons',
        'buttons.addNew': 'Add New',
        'common.filters': 'Filters & Search',
        'search.placeholderInsuredPerson': 'Search by name, email, or ID...',
        'filters.selectGender': 'Select Gender',
        'filters.allGenders': 'All Genders',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gender.other': 'Other',
        'insurance.insuredPersons.noPersons': 'No Insured Persons Found',
        'insurance.insuredPersons.noPersonsFilterDesc': 'No insured persons match your current filters. Try adjusting your search.',
        'insurance.insuredPersons.noPersonsDesc': 'Start by adding a new insured person to manage their details.',
        'buttons.addNewInsuredPerson': 'Add Insured Person',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.email': 'Email',
        'common.phone': 'Phone',
        'common.gender': 'Gender',
        'identification.type': 'ID Type',
        'idType.national_id': 'National ID',
        'idType.insurance_number': 'Insurance No.',
        'idType.passport': 'Passport',
        'identification.number': 'ID Number',
        'common.dateOfBirth': 'Date of Birth',

        // Doctors specific translations
        'doctors.fields.name': 'Name',
        'doctors.fields.licenseNumber': 'License No.',
        'doctors.fields.specialties': 'Specialties',
        'doctors.fields.subSpecialties': 'Sub-Specialties',
        'doctors.fields.phone': 'Phone',
        'doctors.fields.email': 'Email',
        'doctors.fields.city': 'City',
        'doctors.fields.address': 'Address',
        'doctors.fields.status': 'Status', // Already have common.status, but can be specific if needed
        'doctors.fields.tags': 'Tags',
        'doctors.fields.notes': 'Notes',
        'doctors.searchPlaceholder': 'Search by Name, License, Email...',
        'doctors.addNewDoctor': 'Add New Doctor',
        'doctors.editDoctor': 'Edit Doctor',
        'doctors.deleteDoctor': 'Delete Doctor',
        'doctors.deleteConfirmMessage': 'Are you sure you want to delete doctor "{{name}}"? This action cannot be undone.',
        'doctors.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'doctors.createSuccess': 'Doctor "{{name}}" created successfully.',
        'doctors.updateSuccess': 'Doctor "{{name}}" updated successfully.',
        'doctors.deleteSuccess': 'Doctor "{{name}}" deleted successfully.',
        'doctors.bulkDeleteSuccess': 'Successfully deleted {{count}} doctors.',
        'doctors.deleteError': 'Failed to delete doctor "{{name}}". Error: {{error}}',
        'pageTitles.doctorsSingular': 'Doctor', // For consistency
        'pageTitles.doctorsPlural': 'Doctors', // For consistency
        'pageTitles.doctorsMultipleItems': '{{count}} doctors', // For bulk messages
        'emptyStates.noDoctorsTitle': 'No Doctors Found',
        'emptyStates.noDoctorsMessage': 'Start by adding a new doctor to manage their details.',
        'emptyStates.noDoctorsFilterTitle': 'No Doctors Match Filters',
        'emptyStates.noDoctorsFilterMessage': 'Try adjusting your search or filter criteria.',

        // Provider specific (checking existing, adding if necessary)
        'providers.fields.name': 'Provider Name',
        'providers.fields.provider_type': 'Type',
        'providers.fields.city': 'City',
        'providers.fields.status': 'Status',
        'providers.titleMultiple': 'Providers',
        'providers.itemTitleSingular': 'Provider',
        'providers.itemTitlePlural': 'Providers',
        'providers.itemTitlePluralItems': '{{count}} providers',
        'providers.addProvider': 'Add Provider',
        'providers.editProvider': 'Edit Provider',
        'providers.deleteConfirmMessage': 'Are you sure you want to delete provider "{{name}}"? This action cannot be undone.',
        'providers.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'providers.createSuccess': 'Provider "{{name}}" created successfully.',
        'providers.updateSuccess': 'Provider "{{name}}" updated successfully.',
        'providers.deleteError': 'Could not delete provider "{{name}}". Error: {{error}}',
        
        // Linkage specific translations
        'linkage.itemTitleSingular': 'Linkage',
        'linkage.itemTitlePlural': 'Linkages',
        'linkage.addLink': 'Add Linkage',
        'linkage.editLink': 'Edit Linkage',
        'linkage.deleteLink': 'Delete Linkage',
        'linkage.deleteConfirmMessage': 'Are you sure you want to delete this linkage?',
        'linkage.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}?',
        'linkage.createSuccess': 'Linkage created successfully.',
        'linkage.updateSuccess': 'Linkage updated successfully.',
        'linkage.deleteError': 'Failed to delete linkage. Error: {{error}}',
        'fields.startDate': 'Start Date',
        'fields.endDate': 'End Date',
        'fields.affiliationStatus': 'Affiliation Status', // Example, adjust as needed
        'linkage.searchPlaceholder': 'Search by Doctor or Provider name...',
        'linkage.filters.selectProvider': 'Select Provider',
        'linkage.filters.selectDoctor': 'Select Doctor',
        'linkage.filters.selectAffiliationStatus': 'Select Affiliation Status',
        'linkage.noLinkagesFound': 'No Linkages Found',
        'linkage.noLinkagesFilterMessage': 'No linkages match your current filters. Try adjusting your search.',
        'linkage.startAdding': 'Start by adding a new linkage between a doctor and a provider.',
        'pageTitles.providerDoctorLinkageShort': 'Linkages', // Ensure this exists for the tab title',

        // Tasks specific translations
        'tasks.fields.title': 'Title',
        'tasks.fields.description': 'Description',
        'tasks.fields.status': 'Status',
        'tasks.fields.priority': 'Priority',
        'tasks.fields.category': 'Category',
        'tasks.fields.dueDate': 'Due Date',
        'tasks.fields.assignedTo': 'Assigned To',
        'tasks.fields.estimatedHours': 'Estimated Hours',
        'tasks.fields.actualHours': 'Actual Hours',
        'tasks.searchPlaceholder': 'Search tasks...',
        'tasks.addNewTask': 'Add New Task',
        'tasks.editTask': 'Edit Task',
        'tasks.deleteTask': 'Delete Task',
        'tasks.deleteConfirmMessage': 'Are you sure you want to delete task "{{name}}"? This action cannot be undone.',
        'tasks.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'tasks.createSuccess': 'Task "{{name}}" created successfully.',
        'tasks.updateSuccess': 'Task "{{name}}" updated successfully.',
        'tasks.deleteSuccess': 'Task "{{name}}" deleted successfully.',
        'tasks.bulkDeleteSuccess': 'Successfully deleted {{count}} tasks.',
        'tasks.deleteError': 'Failed to delete task "{{name}}". Error: {{error}}',
        'pageTitles.tasks': 'Tasks',
        'pageTitles.tasksSingular': 'Task',
        'pageTitles.tasksPlural': 'Tasks',
        'pageTitles.tasksMultipleItems': '{{count}} tasks',
        'emptyStates.noTasksTitle': 'No Tasks Found',
        'emptyStates.noTasksMessage': 'Start by adding a new task to manage your work.',
        'emptyStates.noTasksFilterTitle': 'No Tasks Match Filters',
        'emptyStates.noTasksFilterMessage': 'Try adjusting your search or filter criteria.',

        // Status translations for tasks
        'status.todo': 'Todo',
        'status.in_progress': 'In Progress',
        'status.done': 'Done',
        'status.cancelled': 'Cancelled',

        // Priority translations
        'priority.low': 'Low',
        'priority.medium': 'Medium',
        'priority.high': 'High',
        'priority.urgent': 'Urgent',
        'filters.allPriorities': 'All Priorities',
        'filters.selectPriority': 'Select Priority',

        // Category translations
        'category.claim_review': 'Claim Review',
        'category.provider_onboarding': 'Provider Onboarding',
        'category.contract_negotiation': 'Contract Negotiation',
        'category.compliance_check': 'Compliance Check',
        'category.data_validation': 'Data Validation',
        'category.system_maintenance': 'System Maintenance',
        'category.training': 'Training',
        'category.general': 'General',
        'filters.allCategories': 'All Categories',
        'filters.selectCategory': 'Select Category',
        
        // Medical Codes specific translations
        'medicalCodes.fields.code': 'Code',
        'medicalCodes.fields.codeSystem': 'Code System',
        'medicalCodes.fields.descriptionEn': 'Description (EN)',
        'medicalCodes.fields.descriptionHe': 'Description (HE)',
        'medicalCodes.fields.tags': 'Tags',
        'medicalCodes.fields.catalogPath': 'Catalog Path',
        'medicalCodes.fields.status': 'Status',
        'medicalCodes.searchPlaceholder': 'Search by code or description...',
        'medicalCodes.addNew': 'Add New Medical Code',
        'medicalCodes.edit': 'Edit Medical Code',
        'medicalCodes.delete': 'Delete Medical Code',
        'medicalCodes.deleteConfirmMessage': 'Are you sure you want to delete medical code "{{name}}"? This action cannot be undone.',
        'medicalCodes.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'medicalCodes.createSuccess': 'Medical code "{{name}}" created successfully.',
        'medicalCodes.updateSuccess': 'Medical code "{{name}}" updated successfully.',
        'medicalCodes.deleteSuccess': 'Medical code "{{name}}" deleted successfully.',
        'medicalCodes.bulkDeleteSuccess': 'Successfully deleted {{count}} medical codes.',
        'medicalCodes.deleteError': 'Failed to delete medical code "{{name}}". Error: {{error}}',
        'medicalCodes.titleMultiple': 'Medical Codes',
        'medicalCodes.itemTitleSingular': 'Medical Code',
        'medicalCodes.itemTitlePluralItems': '{{count}} medical codes',
        'emptyStates.noMedicalCodesTitle': 'No Medical Codes Found',
        'emptyStates.noMedicalCodesMessage': 'Start by adding a new medical code to the system.',
        'emptyStates.noMedicalCodesFilterTitle': 'No Medical Codes Match Filters',
        'emptyStates.noMedicalCodesFilterMessage': 'Try adjusting your search or filter criteria.',
        'filters.allCodeSystems': 'All Code Systems',
        'filters.selectCodeSystem': 'Select Code System',
        'status.deprecated': 'Deprecated',
        'errors.medicalCodeDataMissing': 'Medical code data could not be loaded or is incomplete.',
        'common.noDescription': 'No description available.',
        'common.unknownCode': 'Unknown Code',
        
        // Internal Codes specific translations
        'internalCodes.fields.codeNumber': 'Code Number',
        'internalCodes.fields.descriptionEn': 'Description (EN)',
        'internalCodes.fields.descriptionHe': 'Description (HE)',
        'internalCodes.fields.category_id': 'Category ID', // Keep for consistency
        'internalCodes.fields.categoryPath': 'Category Path',
        'internalCodes.fields.tags': 'Tags',
        'internalCodes.fields.isBillable': 'Billable',
        'internalCodes.fields.isBillableShort.true': 'Billable',
        'internalCodes.fields.isBillableShort.false': 'Not Billable',
        'internalCodes.fields.isActive': 'Active Status', // 'Active' or 'Inactive'
        'internalCodes.searchPlaceholder': 'Search by code, description, or category...',
        'internalCodes.addNew': 'Add New Internal Code',
        'internalCodes.edit': 'Edit Internal Code',
        'internalCodes.deleteConfirmMessage': 'Are you sure you want to delete internal code "{{name}}"? This action cannot be undone.',
        'internalCodes.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'internalCodes.createSuccess': 'Internal code "{{name}}" created successfully.',
        'internalCodes.updateSuccess': 'Internal code "{{name}}" updated successfully.',
        'internalCodes.deleteSuccess': 'Internal code "{{name}}" deleted successfully.',
        'internalCodes.bulkDeleteSuccess': 'Successfully deleted {{count}} internal codes.',
        'internalCodes.deleteError': 'Failed to delete internal code "{{name}}". Error: {{error}}',
        'internalCodes.titleMultiple': 'Internal Codes',
        'internalCodes.itemTitleSingular': 'Internal Code',
        'internalCodes.itemTitlePluralItems': '{{count}} internal codes',
        'emptyStates.noInternalCodesTitle': 'No Internal Codes Found',
        'emptyStates.noInternalCodesMessage': 'Start by adding a new internal code to the system.',
        'emptyStates.noInternalCodesFilterTitle': 'No Internal Codes Match Filters',
        'emptyStates.noInternalCodesFilterMessage': 'Try adjusting your search or filter criteria.',
        'filters.allBillable': 'All (Billable Status)',
        'filters.selectBillable': 'Select Billable Status',
        'errors.internalCodeDataMissing': 'Internal code data could not be loaded or is incomplete.',

        // Insurance Codes specific translations  
        'insuranceCodes.fields.code': 'Code',
        'insuranceCodes.fields.nameEn': 'Name (EN)',
        'insuranceCodes.fields.nameHe': 'Name (HE)', 
        'insuranceCodes.fields.categoryPath': 'Category Path',
        'insuranceCodes.fields.requiresPreAuth': 'Pre-Authorization',
        'insuranceCodes.fields.isActive': 'Status',
        'insuranceCodes.searchPlaceholder': 'Search by code or name...',
        'insuranceCodes.addNew': 'Add New Insurance Code',
        'insuranceCodes.edit': 'Edit Insurance Code',
        'insuranceCodes.delete': 'Delete Insurance Code',
        'insuranceCodes.deleteConfirmMessage': 'Are you sure you want to delete insurance code "{{name}}"? This action cannot be undone.',
        'insuranceCodes.bulkDeleteConfirmMessage': 'Are you sure you want to delete {{count}} {{itemName}}? This action cannot be undone.',
        'insuranceCodes.createSuccess': 'Insurance code "{{name}}" created successfully.',
        'insuranceCodes.updateSuccess': 'Insurance code "{{name}}" updated successfully.',
        'insuranceCodes.deleteSuccess': 'Insurance code "{{name}}" deleted successfully.',
        'insuranceCodes.bulkDeleteSuccess': 'Successfully deleted {{count}} insurance codes.',
        'insuranceCodes.deleteError': 'Failed to delete insurance code "{{name}}". Error: {{error}}',
        'insuranceCodes.titleMultiple': 'Insurance Codes',
        'insuranceCodes.itemTitleSingular': 'Insurance Code',
        'insuranceCodes.itemTitlePlural': 'Insurance Codes',
        'insuranceCodes.itemTitlePluralItems': '{{count}} insurance codes',
        'insuranceCodes.noCodesYetTitle': 'No Insurance Codes Yet',
        'insuranceCodes.noCodesYetDesc': 'Get started by adding a new insurance code.',
        'insuranceCodes.noCodesMatchTitle': 'No Insurance Codes Match Filters',
        'insuranceCodes.noCodesMatchDesc': 'Try adjusting your search or filter criteria.',
        'insuranceCodes.filterByCategory': 'Filter by category...',
        'insuranceCodes.filters.selectPreAuth': 'Select Pre-Auth',
        'filters.allPreAuth': 'All Pre-Auth',
        'common.required': 'Required',
        'common.notRequired': 'Not Required',
        
        // Common bulk actions
        'bulkActions.selectionModeActiveTitle': 'Selection Mode Activated for {{mode}}',
        'bulkActions.selectionModeActiveDesc': 'Select {{entity}} to {{mode}}.',
        'bulkActions.noItemsSelectedTitle': 'No Items Selected',
        'bulkActions.selectItemsPrompt': 'Please select items to {{mode}}.',
        'bulkActions.selectOneToEditTitle': 'Select One Item',
        'bulkActions.selectOneToEditDesc': 'Please select only one {{entity}} to edit.',
        'bulkActions.selectedCount': '{{count}} selected',
        'bulkActions.selectItemsPromptShort': 'Select items to {{mode}}',
        'bulkActions.selectAllVisible': 'Select all visible',
        'bulkActions.selectAllRows': 'Select all rows',
        'bulkActions.selectRow': 'Select row',
        'bulkActions.deleteResultTitle': 'Deletion Summary',
        'bulkActions.deleteResultDesc': 'Successfully deleted {{successCount}} {{entity}}, failed to delete {{failCount}}.',
        
        // Common buttons & labels already present or slightly adjusted
        'buttons.import': 'Import',
        'buttons.export': 'Export',
        'buttons.previous': 'Previous',
        'buttons.next': 'Next',
        'buttons.apply': 'Apply',
        'buttons.save': 'Save',
        'buttons.create': 'Create',
        'buttons.update': 'Update',
        'buttons.add': 'Add',
        'buttons.close': 'Close',

        // Common error messages
        'errors.invalidDataTitle': 'Invalid Data',
        'errors.providerDataMissing': 'Provider data could not be loaded or is incomplete.',
        'errors.doctorDataMissing': 'Doctor data could not be loaded or is incomplete.',
        'errors.itemNotFoundTitle': 'Item Not Found',
        'errors.itemNotFoundMessage': 'The requested {{item}} could not be found.',
        'errors.itemNotFoundToEditDesc': 'The selected item could not be found for editing.',
        'errors.fetchFailedGeneral': 'Failed to fetch {{item}}.',
        'errors.dataLoadErrorTitle': 'Data Load Error',
        'errors.partialLoadWarning': 'Some {{entity}} data might be stale or incomplete due to a recent error: {{message}}. Please refresh for the latest data.',

        // Common messages
        'messages.refreshingData': 'Refreshing Data',
        'messages.fetchingLatest': 'Fetching latest {{item}}...',
        'messages.success': 'Success!',
        'messages.updatingData': 'Updating {{item}}...',
        'messages.loadingData': 'Loading {{item}}...', // For consistency
        
        // DataTable
        'dataTable.pageInfo': 'Page {{page}} of {{totalPages}}',
        'dataTable.paginationSummary': 'Showing {{start}}-{{end}} of {{total}} {{entity}}',

        // Filters
        'filters.allTypes': 'All Types',
        'filters.allSpecialties': 'All Specialties',
        'filters.allCities': 'All Cities',
        'filters.selectSpecialty': 'Select Specialty',
        'filters.selectCity': 'Select City',
        'filters.allLegalTypes': 'All Legal Types',

        // View Switcher
        'viewSwitcher.cardView': 'Card View',
        'viewSwitcher.tableView': 'Table View',

        // Import Dialog
        'import.noRecordsTitle': 'No Records To Import',
        'import.noRecordsDesc': 'The uploaded file does not contain any records to import.',
        'import.noValidRecordsTitle': 'No Valid Records',
        'import.noValidRecordsDesc': 'No valid records found in the file to import for {{entity}}.',
        'import.completedTitle': 'Import Completed',
        'import.completedDesc': 'Successfully imported {{successCount}} records. {{errorCount}} records failed for {{entity}}.',
        'import.featureNotImplemented': 'Import feature for {{entity}} is not yet implemented.',
        'import.comingSoonTitle': 'Import Coming Soon',
        'import.noFileTitle': 'No File Selected',
        'import.noFileDesc': 'Please select a file to import.',
        
        // General
        'common.actions': 'Actions',
        'common.filtersAndSort': 'Filters & Sort',
        'common.sortBy': 'Sort By',
        'common.search': 'Search',
        'common.unknownProvider': 'Unknown Provider',
        'common.unknownDoctor': 'Unknown Doctor',
        'common.item': 'Item',
        'common.items': 'Items',
        'common.data': 'Data',
        'common.noResultsFound': 'No {{item}} found',
        'common.tryAdjustingFilters': 'Try adjusting your search or filters.',
        'common.errorLoading': 'Error loading {{item}}.',
        'common.confirmDeleteTitle': 'Confirm Delete {{item}} ({{count}})',
        'common.confirmDeleteDescription': 'Are you sure you want to delete {{item}} ({{count}})? This action cannot be undone.',
        'common.langCode': 'en', // For logic based on language
        'common.cancel': 'Cancel',
        'common.confirm': 'Confirm',
        'common.featureComingSoonTitle': 'Feature Coming Soon',
        'common.featureComingSoonDesc': '{{featureName}} will be available soon.'
    },
    'he': {
        // ... (Hebrew translations)
        'common.error': 'שגיאה',
        'search.placeholderInsuredPerson': 'חפש לפי שם, אימייל או ת.ז...',
        'buttons.refresh': 'רענן',
        'common.featureComingSoonDetailed': 'יכולות מלאות של {{featureName}} יהיו זמינות בקרוב.',
        'buttons.viewError': 'הצג שגיאה',
        'buttons.enable': 'הפעל',
        'buttons.disable': 'השבת',
        'buttons.configure': 'הגדר',
        'buttons.learnMore': 'למד עוד',
        'buttons.manage': 'נהל',
        'pageTitles.networkManagement': 'ניהול רשת ספקים',
        'networkManagement.pageDescription': 'נהל ספקים, רופאים וההתקשרויות ביניהם.',
        'pageTitles.providerDoctorLinkageShort': 'התקשרויות',
        'adminSettings.systemHealth.title': 'לוח בקרה - תקינות המערכת',
        'adminSettings.systemHealth.pageDescription': 'סקירת מצב רכיבי המערכת ומדדי ביצועים.',
        'adminSettings.systemHealth.databaseService': 'שירות מסד נתונים',
        'adminSettings.systemHealth.apiGateway': 'שער API',
        'adminSettings.systemHealth.backgroundJobs': 'מעבד עבודות רקע',
        'adminSettings.systemHealth.securityServices': 'שירותי אבטחה',
        'adminSettings.systemHealth.systemLoad': 'עומס מערכת כללי',
        'adminSettings.systemHealth.loadDescription': 'ניצול נוכחי של CPU וזיכרון.',
        'adminSettings.systemHealth.status.operational': 'תקין',
        'adminSettings.systemHealth.status.degraded_performance': 'ביצועים ירודים',
        'adminSettings.systemHealth.status.outage': 'תקלה',
        'adminSettings.integrations.title': 'ניהול אינטגרציות',
        'adminSettings.integrations.pageDescription': 'חבר והגדר שירותי צד שלישי ו-API.',
        'adminSettings.integrations.emailService.name': 'שירות אימייל טרנזקציוני',
        'adminSettings.integrations.emailService.desc': 'לשליחת התראות מערכת והודעות.',
        'adminSettings.integrations.paymentGateway.name': 'שער תשלומים',
        'adminSettings.integrations.paymentGateway.desc': 'לעיבוד תשלומים עבור תכונות פרימיום.',
        'adminSettings.integrations.analytics.name': 'פלטפורמת אנליטיקה חיצונית',
        'adminSettings.integrations.analytics.desc': 'סנכרן נתונים עם כלי האנליטיקה המועדף עליך.',
        'adminSettings.integrations.reportingApi.name': 'API דיווח חיצוני',
        'adminSettings.integrations.reportingApi.desc': 'התחבר למערכות דיווח חיצוניות.',
        'integrationStatus.active': 'פעיל',
        'integrationStatus.inactive': 'לא פעיל',
        'integrationStatus.pending_configuration': 'ממתין להגדרה',
        'integrationStatus.error': 'שגיאה',
        'errors.rateLimitExceeded': 'השירות עמוס זמנית. אנא נסה שוב בעוד מספר רגעים.',
        'errors.genericApiError': 'אירעה שגיאה. אנא נסה שוב.',
        'errors.genericFetchError': 'לא ניתן היה לטעון נתונים.',
        'common.success': 'הצלחה',
        'common.warning': 'אזהרה',
        'errors.fetchDropdownError': 'נכשל בטעינת אפשרויות סינון.',
        'common.notSet': 'לא זמין',
        'common.invalidDate': 'תאריך לא תקין',
        'common.confirmDelete': 'האם אתה בטוח שברצונך למחוק פריט זה?',
        'common.deleteSuccess': 'הפריט נמחק בהצלחה.',
        'common.deleteError': 'נכשל במחיקת הפריט.',
        'common.updateSuccess': 'הפריט עודכן בהצלחה.',
        'common.createSuccess': 'הפריט נוצר בהצלחה.',
        'common.saveError': 'נכשל בשמירת הפריט.',
        'common.featureComingSoonTitle': 'תכונה תהיה זמינה בקרוב',
        'insurance.insuredPersons.dialogComingSoon': 'הדיאלוג להוספה/עריכה של מבוטחים ייושם בקרוב.',
        'rfc.dialogComingSoon': 'הדיאלוג לבקשות להתחייבות ייושם בקרוב.',
        'common.createdOn': 'נוצר ב',
        'fields.procedureDate': 'תאריך פרוצדורה',
        'fields.insured': 'מבוטח',
        'fields.provider': 'ספק',
        'fields.doctor': 'רופא',
        'fields.policyNumber': 'מספר פוליסה',
        'fields.procedures': 'פרוצדורות',
        'fields.approvedAmount': 'סכום מאושר',
        'buttons.viewDetails': 'הצג פרטים',
        'rfc.viewDetailsComingSoon': 'הצגת פרטי בקשה להתחייבות תהיה זמינה בקרוב.',
        'rfc.titleMultiple': 'בקשות להתחייבות',
        'buttons.addNewRFC': 'בקשה חדשה',
        'search.placeholderRFC': 'חפש בקשות...',
        'filters.allStatuses': 'כל הסטטוסים',
        'status.draft': 'טיוטה',
        'status.submitted': 'הוגש',
        'status.inReview': 'בבדיקה',
        'status.approved': 'מאושר',
        'status.rejected': 'נדחה',
        'filters.selectStatus': 'בחר סטטוס',
        'filters.selectProvider': 'בחר ספק',
        'filters.allProviders': 'כל הספקים',
        'buttons.resetFilters': 'אפס פילטרים',
        'buttons.retry': 'נסה שוב',
        'messages.loadingData': 'טוען {{item}}...',
        'rfc.noRFCsMatchTitle': 'אין בקשות התואמות לסינון',
        'rfc.noRFCsMatchFilterDesc': 'נסה לשנות את הפילטרים או ליצור בקשה חדשה.',
        'rfc.noRFCsDesc': 'לא נמצאו בקשות. התחל ביצירת בקשה חדשה להתחייבות.',
        'common.unknown': 'לא ידוע',
        'fields.created': 'נוצר',
        'fields.notes': 'הערות',
        'errors.partialLoadFailure': 'חלק מהנתונים לא נטענו. ייתכן שהפונקציונליות מוגבלת. אנא רענן כדי לנסות שוב.',
        'errors.fetchFailedSingular': 'נכשל בטעינת {{entity}}.',
        'insurance.insuredPersons.title': 'מבוטחים',
        'buttons.addNew': 'הוסף חדש',
        'common.filters': 'סינון וחיפוש',
        'filters.selectGender': 'בחר מין',
        'filters.allGenders': 'כל המינים',
        'gender.male': 'זכר',
        'gender.female': 'נקבה',
        'gender.other': 'אחר',
        'insurance.insuredPersons.noPersons': 'לא נמצאו מבוטחים',
        'insurance.insuredPersons.noPersonsFilterDesc': 'אין מבוטחים התואמים לסינון הנוכחי. נסה לשנות את החיפוש.',
        'insurance.insuredPersons.noPersonsDesc': 'התחל בהוספת מבוטח חדש כדי לנהל את פרטיו.',
        'buttons.addNewInsuredPerson': 'הוסף מבוטח חדש',
        'common.edit': 'ערוך',
        'common.delete': 'מחק',
        'common.email': 'אימייל',
        'common.phone': 'טלפון',
        'common.gender': 'מין',
        'identification.type': 'סוג זיהוי',
        'idType.national_id': 'ת.ז.',
        'idType.insurance_number': 'מספר ביטוח',
        'idType.passport': 'דרכון',
        'identification.number': 'מספר זיהוי',
        'common.dateOfBirth': 'תאריך לידה',

        // Doctors specific translations (Hebrew)
        'doctors.fields.name': 'שם',
        'doctors.fields.licenseNumber': 'מספר רישיון',
        'doctors.fields.specialties': 'התמחויות',
        'doctors.fields.subSpecialties': 'תת-התמחויות',
        'doctors.fields.phone': 'טלפון',
        'doctors.fields.email': 'אימייל',
        'doctors.fields.city': 'עיר',
        'doctors.fields.address': 'כתובת',
        // 'doctors.fields.status': 'סטטוס', // common.status already exists in HE
        'doctors.fields.tags': 'תגיות',
        'doctors.fields.notes': 'הערות',
        'doctors.searchPlaceholder': 'חפש לפי שם, רישיון, אימייל...',
        'doctors.addNewDoctor': 'הוסף רופא חדש',
        'doctors.editDoctor': 'ערוך רופא',
        'doctors.deleteDoctor': 'מחק רופא',
        'doctors.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את הרופא "{{name}}"? לא ניתן לבטל פעולה זו.',
        'doctors.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'doctors.createSuccess': 'הרופא "{{name}}" נוצר בהצלחה.',
        'doctors.updateSuccess': 'הרופא "{{name}}" עודכן בהצלחה.',
        'doctors.deleteSuccess': 'הרופא "{{name}}" נמחק בהצלחה.',
        'doctors.bulkDeleteSuccess': 'נמחקו בהצלחה {{count}} רופאים.',
        'doctors.deleteError': 'נכשל במחיקת הרופא "{{name}}". שגיאה: {{error}}',
        'pageTitles.doctorsSingular': 'רופא',
        'pageTitles.doctorsPlural': 'רופאים',
        'pageTitles.doctorsMultipleItems': '{{count}} רופאים',
        'emptyStates.noDoctorsTitle': 'לא נמצאו רופאים',
        'emptyStates.noDoctorsMessage': 'התחל על ידי הוספת רופא חדש לניהול פרטיו.',
        'emptyStates.noDoctorsFilterTitle': 'אין רופאים התואמים לסינון',
        'emptyStates.noDoctorsFilterMessage': 'נסה להתאים את החיפוש או את קריטריוני הסינון.',

        // Provider specific (checking existing, adding if necessary - Hebrew)
        'providers.fields.name': 'שם הספק',
        'providers.fields.provider_type': 'סוג',
        'providers.fields.city': 'עיר',
        // 'providers.fields.status': 'סטטוס', // common.status
        'providers.titleMultiple': 'ספקים',
        'providers.itemTitleSingular': 'ספק',
        'providers.itemTitlePlural': 'ספקים',
        'providers.itemTitlePluralItems': '{{count}} ספקים',
        'providers.addProvider': 'הוסף ספק',
        'providers.editProvider': 'ערוך ספק',
        'providers.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את הספק "{{name}}"? לא ניתן לבטל פעולה זו.',
        'providers.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'providers.createSuccess': 'הספק "{{name}}" נוצר בהצלחה.',
        'providers.updateSuccess': 'הספק "{{name}}" עודכן בהצלחה.',
        'providers.deleteError': 'לא ניתן למחוק את הספק "{{name}}". שגיאה: {{error}}',

        // Linkage specific translations (Hebrew)
        'linkage.itemTitleSingular': 'התקשרות',
        'linkage.itemTitlePlural': 'התקשרויות',
        'linkage.addLink': 'הוסף התקשרות',
        'linkage.editLink': 'ערוך התקשרות',
        'linkage.deleteLink': 'מחק התקשרות',
        'linkage.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק התקשרות זו?',
        'linkage.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}?',
        'linkage.createSuccess': 'ההתקשרות נוצרה בהצלחה.',
        'linkage.updateSuccess': 'ההתקשרות עודכנה בהצלחה.',
        'linkage.deleteError': 'נכשל במחיקת ההתקשרות. שגיאה: {{error}}',
        'fields.startDate': 'תאריך התחלה',
        'fields.endDate': 'תאריך סיום',
        'fields.affiliationStatus': 'סטטוס התקשרות',
        'linkage.searchPlaceholder': 'חפש לפי שם רופא או ספק...',
        'linkage.filters.selectProvider': 'בחר ספק',
        'linkage.filters.selectDoctor': 'בחר רופא',
        'linkage.filters.selectAffiliationStatus': 'בחר סטטוס התקשרות',
        'linkage.noLinkagesFound': 'לא נמצאו התקשרויות',
        'linkage.noLinkagesFilterMessage': 'לא נמצאו התקשרויות התואמות לקריטריוני הסינון שלך.',
        'linkage.startAdding': 'התחל על ידי הוספת התקשרות חדשה בין רופא לספק.',
        // pageTitles.providerDoctorLinkageShort already exists

        // Tasks specific translations (Hebrew)
        'tasks.fields.title': 'כותרת',
        'tasks.fields.description': 'תיאור',
        'tasks.fields.status': 'סטטוס',
        'tasks.fields.priority': 'עדיפות',
        'tasks.fields.category': 'קטגוריה',
        'tasks.fields.dueDate': 'תאריך יעד',
        'tasks.fields.assignedTo': 'מוקצה ל',
        'tasks.fields.estimatedHours': 'שעות משוערות',
        'tasks.fields.actualHours': 'שעות בפועל',
        'tasks.searchPlaceholder': 'חפש משימות...',
        'tasks.addNewTask': 'הוסף משימה חדשה',
        'tasks.editTask': 'ערוך משימה',
        'tasks.deleteTask': 'מחק משימה',
        'tasks.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את המשימה "{{name}}"? לא ניתן לבטל פעולה זו.',
        'tasks.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'tasks.createSuccess': 'המשימה "{{name}}" נוצרה בהצלחה.',
        'tasks.updateSuccess': 'המשימה "{{name}}" עודכנה בהצלחה.',
        'tasks.deleteSuccess': 'המשימה "{{name}}" נמחקה בהצלחה.',
        'tasks.bulkDeleteSuccess': 'נמחקו בהצלחה {{count}} משימות.',
        'tasks.deleteError': 'נכשל במחיקת המשימה "{{name}}". שגיאה: {{error}}',
        'pageTitles.tasks': 'משימות',
        'pageTitles.tasksSingular': 'משימה',
        'pageTitles.tasksPlural': 'משימות',
        'pageTitles.tasksMultipleItems': '{{count}} משימות',
        'emptyStates.noTasksTitle': 'לא נמצאו משימות',
        'emptyStates.noTasksMessage': 'התחל על ידי הוספת משימה חדשה לניהול העבודה שלך.',
        'emptyStates.noTasksFilterTitle': 'אין משימות התואמות לסינון',
        'emptyStates.noTasksFilterMessage': 'נסה להתאים את החיפוש או את קריטריוני הסינון.',

        // Status translations for tasks (Hebrew)
        'status.todo': 'לביצוע',
        'status.in_progress': 'בביצוע',
        'status.done': 'הושלם',
        'status.cancelled': 'בוטל',

        // Priority translations (Hebrew)
        'priority.low': 'נמוך',
        'priority.medium': 'בינוני',
        'priority.high': 'גבוה',
        'priority.urgent': 'דחוף',
        'filters.allPriorities': 'כל העדיפויות',
        'filters.selectPriority': 'בחר עדיפות',

        // Category translations (Hebrew)
        'category.claim_review': 'בדיקת תביעות',
        'category.provider_onboarding': 'רישום ספקים',
        'category.contract_negotiation': 'משא ומתן על חוזים',
        'category.compliance_check': 'בדיקת תאימות',
        'category.data_validation': 'אימות נתונים',
        'category.system_maintenance': 'תחזוקת מערכת',
        'category.training': 'הדרכה',
        'category.general': 'כללי',
        'filters.allCategories': 'כל הקטגוריות',
        'filters.selectCategory': 'בחר קטגוריה',

        // Medical Codes specific translations (Hebrew)
        'medicalCodes.fields.code': 'קוד',
        'medicalCodes.fields.codeSystem': 'מערכת קידוד',
        'medicalCodes.fields.descriptionEn': 'תיאור (אנגלית)',
        'medicalCodes.fields.descriptionHe': 'תיאור (עברית)',
        'medicalCodes.fields.tags': 'תגיות',
        'medicalCodes.fields.catalogPath': 'נתיב בקטלוג',
        'medicalCodes.fields.status': 'סטטוס',
        'medicalCodes.searchPlaceholder': 'חפש לפי קוד או תיאור...',
        'medicalCodes.addNew': 'הוסף קוד רפואי חדש',
        'medicalCodes.edit': 'ערוך קוד רפואי',
        'medicalCodes.delete': 'מחק קוד רפואי',
        'medicalCodes.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את הקוד הרפואי "{{name}}"? לא ניתן לבטל פעולה זו.',
        'medicalCodes.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'medicalCodes.createSuccess': 'הקוד הרפואי "{{name}}" נוצר בהצלחה.',
        'medicalCodes.updateSuccess': 'הקוד הרפואי "{{name}}" עודכן בהצלחה.',
        'medicalCodes.deleteSuccess': 'הקוד הרפואי "{{name}}" נמחק בהצלחה.',
        'medicalCodes.bulkDeleteSuccess': 'נמחקו בהצלחה {{count}} קודים רפואיים.',
        'medicalCodes.deleteError': 'נכשל במחיקת הקוד הרפואי "{{name}}". שגיאה: {{error}}',
        'medicalCodes.titleMultiple': 'קודים רפואיים',
        'medicalCodes.itemTitleSingular': 'קוד רפואי',
        'medicalCodes.itemTitlePluralItems': '{{count}} קודים רפואיים',
        'emptyStates.noMedicalCodesTitle': 'לא נמצאו קודים רפואיים',
        'emptyStates.noMedicalCodesMessage': 'התחל על ידי הוספת קוד רפואי חדש למערכת.',
        'emptyStates.noMedicalCodesFilterTitle': 'אין קודים רפואיים התואמים לסינון',
        'emptyStates.noMedicalCodesFilterMessage': 'נסה להתאים את החיפוש או את קריטריוני הסינון.',
        'filters.allCodeSystems': 'כל מערכות הקידוד',
        'filters.selectCodeSystem': 'בחר מערכת קידוד',
        'status.deprecated': 'הופסק שימוש',
        'errors.medicalCodeDataMissing': 'נתוני הקוד הרפואי לא נטענו או שהם חלקיים.',
        'common.noDescription': 'אין תיאור זמין.',
        'common.unknownCode': 'קוד לא ידוע',

        // Internal Codes specific translations (Hebrew)
        'internalCodes.fields.codeNumber': 'מספר קוד',
        'internalCodes.fields.descriptionEn': 'תיאור (אנגלית)',
        'internalCodes.fields.descriptionHe': 'תיאור (עברית)',
        'internalCodes.fields.category_id': 'מזהה קטגוריה',
        'internalCodes.fields.categoryPath': 'נתיב קטגוריה',
        'internalCodes.fields.tags': 'תגיות',
        'internalCodes.fields.isBillable': 'ניתן לחיוב',
        'internalCodes.fields.isBillableShort.true': 'לחיוב',
        'internalCodes.fields.isBillableShort.false': 'לא לחיוב',
        'internalCodes.fields.isActive': 'סטטוס פעילות',
        'internalCodes.searchPlaceholder': 'חפש לפי קוד, תיאור או קטגוריה...',
        'internalCodes.addNew': 'הוסף קוד פנימי חדש',
        'internalCodes.edit': 'ערוך קוד פנימי',
        'internalCodes.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את הקוד הפנימי "{{name}}"? לא ניתן לבטל פעולה זו.',
        'internalCodes.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'internalCodes.createSuccess': 'הקוד הפנימי "{{name}}" נוצר בהצלחה.',
        'internalCodes.updateSuccess': 'הקוד הפנימי "{{name}}" עודכן בהצלחה.',
        'internalCodes.deleteSuccess': 'הקוד הפנימי "{{name}}" נמחק בהצלחה.',
        'internalCodes.bulkDeleteSuccess': 'נמחקו בהצלחה {{count}} קודים פנימיים.',
        'internalCodes.deleteError': 'נכשל במחיקת הקוד הפנימי "{{name}}". שגיאה: {{error}}',
        'internalCodes.titleMultiple': 'קודים פנימיים',
        'internalCodes.itemTitleSingular': 'קוד פנימי',
        'internalCodes.itemTitlePluralItems': '{{count}} קודים פנימיים',
        'emptyStates.noInternalCodesTitle': 'לא נמצאו קודים פנימיים',
        'emptyStates.noInternalCodesMessage': 'התחל על ידי הוספת קוד פנימי חדש למערכת.',
        'emptyStates.noInternalCodesFilterTitle': 'אין קודים פנימיים התואמים לסינון',
        'emptyStates.noInternalCodesFilterMessage': 'נסה להתאים את החיפוש או את קריטריוני הסינון.',
        'filters.allBillable': 'הכל (סטטוס חיוב)',
        'filters.selectBillable': 'בחר סטטוס חיוב',
        'errors.internalCodeDataMissing': 'נתוני הקוד הפנימי לא נטענו או שהם חלקיים.',

        // Insurance Codes specific translations (Hebrew)
        'insuranceCodes.fields.code': 'קוד',
        'insuranceCodes.fields.nameEn': 'שם (אנגלית)',
        'insuranceCodes.fields.nameHe': 'שם (עברית)', 
        'insuranceCodes.fields.categoryPath': 'נתיב קטגוריה',
        'insuranceCodes.fields.requiresPreAuth': 'אישור מוקדם',
        'insuranceCodes.fields.isActive': 'סטטוס',
        'insuranceCodes.searchPlaceholder': 'חפש לפי קוד או שם...',
        'insuranceCodes.addNew': 'הוסף קוד ביטוח חדש',
        'insuranceCodes.edit': 'ערוך קוד ביטוח',
        'insuranceCodes.delete': 'מחק קוד ביטוח',
        'insuranceCodes.deleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק את קוד הביטוח "{{name}}"? לא ניתן לבטל פעולה זו.',
        'insuranceCodes.bulkDeleteConfirmMessage': 'האם אתה בטוח שברצונך למחוק {{count}} {{itemName}}? לא ניתן לבטל פעולה זו.',
        'insuranceCodes.createSuccess': 'קוד הביטוח "{{name}}" נוצר בהצלחה.',
        'insuranceCodes.updateSuccess': 'קוד הביטוח "{{name}}" עודכן בהצלחה.',
        'insuranceCodes.deleteSuccess': 'קוד הביטוח "{{name}}" נמחק בהצלחה.',
        'insuranceCodes.bulkDeleteSuccess': 'נמחקו בהצלחה {{count}} קודי ביטוח.',
        'insuranceCodes.deleteError': 'נכשל במחיקת קוד הביטוח "{{name}}". שגיאה: {{error}}',
        'insuranceCodes.titleMultiple': 'קודי ביטוח',
        'insuranceCodes.itemTitleSingular': 'קוד ביטוח',
        'insuranceCodes.itemTitlePlural': 'קודי ביטוח',
        'insuranceCodes.itemTitlePluralItems': '{{count}} קודי ביטוח',
        'insuranceCodes.noCodesYetTitle': 'אין עדיין קודי ביטוח',
        'insuranceCodes.noCodesYetDesc': 'התחל על ידי הוספת קוד ביטוח חדש.',
        'insuranceCodes.noCodesMatchTitle': 'אין קודי ביטוח תואמים לסינון',
        'insuranceCodes.noCodesMatchDesc': 'נסה להתאים את החיפוש או את קריטריוני הסינון.',
        'insuranceCodes.filterByCategory': 'סנן לפי קטגוריה...',
        'insuranceCodes.filters.selectPreAuth': 'בחר אישור מוקדם',
        'filters.allPreAuth': 'כל האישורים המוקדמים',
        'common.required': 'נדרש',
        'common.notRequired': 'לא נדרש',

        // Common bulk actions (Hebrew)
        'bulkActions.selectionModeActiveTitle': 'מצב בחירה הופעל עבור {{mode}}',
        'bulkActions.selectionModeActiveDesc': 'בחר {{entity}} כדי {{mode}}.',
        'bulkActions.noItemsSelectedTitle': 'לא נבחרו פריטים',
        'bulkActions.selectItemsPrompt': 'אנא בחר פריטים כדי {{mode}}.',
        'bulkActions.selectOneToEditTitle': 'בחר פריט אחד',
        'bulkActions.selectOneToEditDesc': 'אנא בחר רק {{entity}} אחד לעריכה.',
        'bulkActions.selectedCount': '{{count}} נבחרו',
        'bulkActions.selectItemsPromptShort': 'בחר פריטים ל {{mode}}',
        'bulkActions.selectAllVisible': 'בחר הכל (הנראים)',
        'bulkActions.selectAllRows': 'בחר את כל השורות',
        'bulkActions.selectRow': 'בחר שורה',
        'bulkActions.deleteResultTitle': 'סיכום מחיקה',
        'bulkActions.deleteResultDesc': 'נמחקו בהצלחה {{successCount}} {{entity}}, נכשלה מחיקת {{failCount}}.',

        // Common buttons & labels (Hebrew)
        'buttons.import': 'ייבוא',
        'buttons.export': 'ייצוא',
        'buttons.previous': 'הקודם',
        'buttons.next': 'הבא',
        'buttons.apply': 'החל',
        'buttons.save': 'שמור',
        'buttons.create': 'צור',
        'buttons.update': 'עדכן',
        'buttons.add': 'הוסף',
        'buttons.close': 'סגור',

        // Common error messages (Hebrew)
        'errors.invalidDataTitle': 'נתונים לא תקינים',
        'errors.providerDataMissing': 'לא ניתן היה לטעון את נתוני הספק או שהם אינם מלאים.',
        'errors.doctorDataMissing': 'לא ניתן היה לטעון את נתוני הרופא או שהם אינם מלאים.',
        'errors.itemNotFoundTitle': 'הפריט לא נמצא',
        'errors.itemNotFoundMessage': 'ה{{item}} המבוקש לא נמצא.',
        'errors.itemNotFoundToEditDesc': 'הפריט שנבחר לא נמצא לצורך עריכה.',
        'errors.fetchFailedGeneral': 'נכשל בטעינת {{item}}.',
        'errors.dataLoadErrorTitle': 'שגיאה בטעינת נתונים',
        'errors.partialLoadWarning': 'יתכן שחלק מנתוני ה{{entity}} אינם עדכניים או חלקיים עקב שגיאה: {{message}}. אנא רענן לקבלת הנתונים העדכניים ביותר.',

        // Common messages (Hebrew)
        'messages.refreshingData': 'מרענן נתונים',
        'messages.fetchingLatest': 'טוען {{item}} עדכניים...',
        'messages.success': 'הצלחה!',
        'messages.updatingData': 'מעדכן {{item}}...',
        // messages.loadingData already exists

        // DataTable (Hebrew)
        'dataTable.pageInfo': 'עמוד {{page}} מתוך {{totalPages}}',
        'dataTable.paginationSummary': 'מציג {{start}}-{{end}} מתוך {{total}} {{entity}}',

        // Filters (Hebrew)
        'filters.allTypes': 'כל הסוגים',
        'filters.allSpecialties': 'כל ההתמחויות',
        'filters.allCities': 'כל הערים',
        'filters.selectSpecialty': 'בחר התמחות',
        'filters.selectCity': 'בחר עיר',
        'filters.allLegalTypes': 'כל הסוגים המשפטיים',

        // View Switcher (Hebrew)
        'viewSwitcher.cardView': 'תצוגת כרטיסים',
        'viewSwitcher.tableView': 'תצוגת טבלה',

        // Import Dialog (Hebrew)
        'import.noRecordsTitle': 'אין רשומות לייבוא',
        'import.noRecordsDesc': 'הקובץ שהועלה אינו מכיל רשומות לייבוא.',
        'import.noValidRecordsTitle': 'אין רשומות תקינות',
        'import.noValidRecordsDesc': 'לא נמצאו רשומות תקינות בקובץ לייבוא עבור {{entity}}.',
        'import.completedTitle': 'הייבוא הושלם',
        'import.completedDesc': 'יובאו בהצלחה {{successCount}} רשומות. {{errorCount}} רשומות נכשלו עבור {{entity}}.',
        'import.featureNotImplemented': 'תכונת הייבוא עבור {{entity}} עדיין לא מיושמת.',
        'import.comingSoonTitle': 'ייבוא יהיה זמין בקרוב',
        'import.noFileTitle': 'לא נבחר קובץ',
        'import.noFileDesc': 'אנא בחר קובץ לייבוא.',

        // General (Hebrew)
        'common.actions': 'פעולות',
        'common.filtersAndSort': 'סינון ומיון',
        'common.sortBy': 'מיין לפי',
        'common.search': 'חיפוש',
        'common.unknownProvider': 'ספק לא ידוע',
        'common.unknownDoctor': 'רופא לא ידוע',
        'common.item': 'פריט',
        'common.items': 'פריטים',
        'common.data': 'נתונים',
        'common.noResultsFound': 'לא נמצאו {{item}}',
        'common.tryAdjustingFilters': 'נסה להתאים את החיפוש או המסננים שלך.',
        'common.errorLoading': 'שגיאה בטעינת {{item}}.',
        'common.confirmDeleteTitle': 'אשר מחיקת {{item}} ({{count}})',
        'common.confirmDeleteDescription': 'האם אתה בטוח שברצונך למחוק {{item}} ({{count}})? לא ניתן לבטל פעולה זו.',
        'common.langCode': 'he', // For logic based on language
        'common.cancel': 'ביטול',
        'common.confirm': 'אישור',
        'common.featureComingSoonTitle': 'תכונה תגיע בקרוב',
        'common.featureComingSoonDesc': '{{featureName}} יהיה זמין בקרוב.'
    }
};

// Simple language hook implementation
export function useLanguageHook() {
  const [language, setLanguage] = useState('en'); // Default to 'en'
  const [isRTL, setIsRTL] = useState(false); // Default RTL status

  useEffect(() => {
    setIsRTL(language === 'he');
    // document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
  }, [language]);

  const t = useCallback((key, options) => {
    // 1. Validate key
    if (typeof key !== 'string') {
      // console.warn('[useLanguageHook] t() called with non-string key:', key);
      return 'INVALID_KEY';
    }

    // 2. Initialize safeOptions robustly
    let S_options = {};
    if (options !== null && typeof options === 'object') {
      S_options = options;
    }
    // S_options is GUARANTEED to be an object.

    // 3. Attempt direct translation (simplified for this example)
    const langToUse = MOCK_TRANSLATIONS[language] ? language : 'en';
    const currentTranslations = MOCK_TRANSLATIONS[langToUse] || MOCK_TRANSLATIONS['en']; // Fallback to 'en' translations if langToUse is invalid
    const translatedString = currentTranslations[key];

    if (typeof translatedString === 'string') {
      // Basic variable replacement (e.g. {{item}})
      if (S_options && typeof S_options === 'object') {
          let resultString = translatedString;
          for (const placeholderKey in S_options) {
              if (Object.prototype.hasOwnProperty.call(S_options, placeholderKey) && placeholderKey !== 'defaultValue') {
                  resultString = resultString.replace(new RegExp(`{{${placeholderKey}}}`, 'g'), S_options[placeholderKey]);
              }
          }
          return resultString;
      }
      return translatedString;
    }
    
    // Fallback logic:
    if (S_options && typeof S_options.defaultValue === 'string') {
      return S_options.defaultValue;
    }
    
    // Final fallback: return the key itself
    // console.warn(`[useLanguageHook] Key "${key}" not found for language "${language}", no valid defaultValue. Returning key.`);
    return key;
  }, [language]); // `t` function now only changes if `language` changes

  return { t, language, setLanguage, isRTL };
}
